#
#  Yaml CI config for Gitlab See. http://docs.gitlab.com/ce/ci/yaml/README.html
#

image: docker-registry.oxfordnanolabs.local:5000/ont-base-ubuntu:16.04

stages:
    - build
    - test
    - release

before_script:
    - make deps
    - make checkout

wheel:
    stage: build
    script:
        - CI=True make wheel
    except:
        - tags
    artifacts:
        paths:
            - dist

unit_test:
    stage: test
    script:
        - CI=True make unitTestFromScratch
    except:
        - tags

acceptance_test:
    stage: test
    script:
        - CI=True make acceptanceTestFromScratch
    except:
        - tags

dev_env_test:
    stage: test
    script:
        - CI=True make cleanDevEnv
    except:
        - tags

build_and_upload_artefact:
    stage: release
    script:
        - apt-get install -y openssh-client
        - eval $(ssh-agent -s)
        #  PYPI_KEY and PYPI_HOST should set up as project variables on Gitlab
        #  PYPI_KEY is private key produced by ssh-keygen
        - ssh-add <(set +x; echo "$PYPI_KEY")
        - scp -o StrictHostKeyChecking=no dist/* gitlab-ci-pypi@${PYPI_HOST}:/opt/ont-pypi/site-packages/
    only:
        - /^dev$/
