#
#  Yaml CI config for Gitlab See. http://docs.gitlab.com/ce/ci/yaml/README.html
#

image: git.oxfordnanolabs.local:4567/algorithm/sloika_docker:14.04-latest

stages:
    - build
    - test
    - release

wheel:
    stage: build
    script:
        - make wheel
    artifacts:
        paths:
            - dist/*.whl
    only:
        - release
        - master
        - /^ci_*/

unit_xenial:
    stage: test
    script:
        - make unitTestFromScratch
    only:
        - release
        - master
        - /^ci_*/

test:
    image: git.oxfordnanolabs.local:4567/algorithm/sloika_docker:14.04-latest
    stage: test
    script:
        - make cleanDevEnv
        - make
    except:
        - release
        - master
        - /^ci_*/

unit_trusty:
    image: git.oxfordnanolabs.local:4567/algorithm/sloika_docker:14.04-latest
    stage: test
    script:
        - make unitTestFromScratch
    only:
        - release
        - master
        - /^ci_*/

workflow:
    stage: test
    before_script:
        - make cleanDevEnv
    script:
        - apt-get install -y bwa
        - make workflow
    only:
        - release
        - master
        - /^ci_*/

pip_install_dot:
    stage: test
    before_script:
        - apt-get install -y python-virtualenv python2.7 python3 python-dev python3-dev
        - virtualenv --python=python3 hoho
        - source hoho/bin/activate && pip install pip --upgrade && pip install numpy cython
    script:
        - source hoho/bin/activate && pip install . --trusted-host pypi.oxfordnanolabs.local --index-url https://pypi.oxfordnanolabs.local/simple/
    only:
        - release
        - master
        - /^ci_*/

wheel_upload:
    stage: release
    before_script:
        - apt-get install -y openssh-client
        - eval $(ssh-agent -s)
    script:
        - ssh-add <(set +x; echo "$PYPI_KEY")
        - scp -v -o StrictHostKeyChecking=no dist/* gitlab-ci-pypi@${PYPI_HOST}:/opt/ont-pypi/site-packages/
    only:
        - release@algorithm/sloika
        - master@algorithm/sloika
