#
#  Yaml CI config for Gitlab See. http://docs.gitlab.com/ce/ci/yaml/README.html
#

image: docker-registry.oxfordnanolabs.local:5000/ont-base-ubuntu:16.04

stages:
    - build
    - test
    - release

before_script:
    - make deps
    - make checkout

wheel:
    stage: build
    script:
        - make wheel
    artifacts:
        paths:
            - dist

ubuntu_14_04:
    stage: test
    image: docker-registry.oxfordnanolabs.local:5000/ont-base-ubuntu:14.04
    script:
        - CI=True make cleanDevEnv
        - CI=True make
    except:
        - tags

unit:
    stage: test
    script:
        - make unitTestFromScratch

acceptance:
    stage: test
    script:
        - make acceptanceTestFromScratch

dev_env_and_style:
    stage: test
    script:
        - make cleanDevEnv
        - make pep8

pip_install_dot:
    stage: test
    before_script:
        - apt-get install -y virtualenv python2.7
        - virtualenv --python=python2.7 hoho
        - source hoho/bin/activate && pip install future
    script:
        - source hoho/bin/activate && pip install . --trusted-host pypi.oxfordnanolabs.local --index-url https://pypi.oxfordnanolabs.local/simple/

upload_artefact:
    stage: release
    before_script:
        - apt-get install -y openssh-client
        - eval $(ssh-agent -s)
    script:
        - ssh-add <(set +x; echo "$PYPI_KEY")
        - scp -v -o StrictHostKeyChecking=no dist/* gitlab-ci-pypi@${PYPI_HOST}:/opt/ont-pypi/site-packages/
    only:
        - master@algorithm/sloika
        - dev@algorithm/sloika
