#
#  Yaml CI config for Gitlab See. http://docs.gitlab.com/ce/ci/yaml/README.html
#

image: git.oxfordnanolabs.local:4567/algorithm/sloika_docker:14.04-latest

stages:
    - build
    - test
    - release

before_script:
    - make ciCheckout

wheel:
    stage: build
    script:
        - make wheelPy3
    artifacts:
        paths:
            - dist/*.whl

unit_xenial:
    stage: test
    script:
        - make unitTestFromScratchPy3
    only:
        - release
        - master
        - /^ci_*/

acceptance_xenial:
    stage: test
    script:
        - make acceptanceTestFromScratchPy3
    only:
        - release
        - master
        - /^ci_*/

unit_trusty:
    image: git.oxfordnanolabs.local:4567/algorithm/sloika_docker:14.04-latest
    stage: test
    script:
        - make unitTestFromScratchPy3

acceptance_trusty:
    image: git.oxfordnanolabs.local:4567/algorithm/sloika_docker:14.04-latest
    stage: test
    script:
        - make acceptanceTestFromScratchPy3

workflow:
    stage: test
    before_script:
        - make ciCheckout
        - make cleanDevEnvPy3
    script:
        - make workflow

dev_env_and_style:
    stage: test
    script:
        - make cleanDevEnvPy3

pip_install_dot:
    stage: test
    before_script:
        - apt-get install -y virtualenv python2.7 python3 python-dev python3-dev
        - virtualenv --python=python3 hoho
        - source hoho/bin/activate && pip install numpy cython
    script:
        - source hoho/bin/activate && pip install . --trusted-host pypi.oxfordnanolabs.local --index-url https://pypi.oxfordnanolabs.local/simple/

wheel_upload:
    stage: release
    before_script:
        - apt-get install -y openssh-client
        - eval $(ssh-agent -s)
    script:
        - ssh-add <(set +x; echo "$PYPI_KEY")
        - scp -v -o StrictHostKeyChecking=no dist/* gitlab-ci-pypi@${PYPI_HOST}:/opt/ont-pypi/site-packages/
    only:
        - release@algorithm/sloika
        - master@algorithm/sloika
