#
#  Yaml CI config for Gitlab See. http://docs.gitlab.com/ce/ci/yaml/README.html
#

image: docker-registry.oxfordnanolabs.local:5000/ont-base-ubuntu:16.04

stages:
    - build
    - test
    - release

before_script:
    - make deps
    - make checkout

wheel:
    stage: build
    script:
        - make wheel
    artifacts:
        paths:
            - dist/*.whl

wheel_py3:
    stage: build
    script:
        - make wheelPy3
    artifacts:
        paths:
            - dist/*.whl

tox:
    stage: test
    script:
        - make toxTestFromScratchPy2
        - make toxTestFromScratchPy3

unit_xenial:
    stage: test
    script:
        - make unitTestFromScratch

acceptance_xenial:
    stage: test
    script:
        - make acceptanceTestFromScratch

unit_trusty:
    image: docker-registry.oxfordnanolabs.local:5000/ont-base-ofan-dev:14.04
    stage: test
    script:
        - make unitTestFromScratch

acceptance_trusty:
    image: docker-registry.oxfordnanolabs.local:5000/ont-base-ofan-dev:14.04
    stage: test
    script:
        - make acceptanceTestFromScratch

dev_env_and_style:
    stage: test
    script:
        - make cleanDevEnv
        - make pep8

pip_install_dot:
    stage: test
    before_script:
        - apt-get install -y virtualenv python2.7 python-dev python3-dev
        - virtualenv --python=python2.7 hoho
        - source hoho/bin/activate && pip install numpy cython future
    script:
        - source hoho/bin/activate && pip install . --trusted-host pypi.oxfordnanolabs.local --index-url https://pypi.oxfordnanolabs.local/simple/

wheel_upload:
    stage: release
    before_script:
        - apt-get install -y openssh-client
        - eval $(ssh-agent -s)
    script:
        - ssh-add <(set +x; echo "$PYPI_KEY")
        - scp -v -o StrictHostKeyChecking=no dist/* gitlab-ci-pypi@${PYPI_HOST}:/opt/ont-pypi/site-packages/
    only:
        - release@algorithm/sloika
        - master@algorithm/sloika
