#
#  Yaml CI config for Gitlab See. http://docs.gitlab.com/ce/ci/yaml/README.html
#

image: docker-registry.oxfordnanolabs.local:5000/ont-base-ubuntu:16.04

stages:
    - test
    - release

before_script:
    - make deps

do_testing:
    stage: test
    script:
        - make testFromScratch
    except:
        - tags

do_release:
    stage: release
    script:
        #  Build project
        - python setup.py sdist
        #  Going to push project via ssh.
        #  PYPI_KEY and PYPI_HOST should set up as project variables on Gitlab
        #  PYPI_KEY is private key produced by ssh-keygen
        - apt-get install -y openssh-client
        - eval $(ssh-agent -s)
        - ssh-add <(set +x; echo "$PYPI_KEY")
        - scp -o StrictHostKeyChecking=no dist/* gitlab-ci-pypi@${PYPI_HOST}:/opt/ont-pypi/site-packages/
    only:
        #  Only do a release of tags marked explicit as release (match this regular expression)
        - /^release_.*$/
    except:
        #  Do look for tags in branches
        - branches

